name: Documentation Improvement
description: Improve request for mono v2-runtime's documentation
labels: ["documentation", "triage"]
assignees:
  - 

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this documentation improvement request.
        Only documentation related request are accepted, so please refrain yourself from submitting any other requests, including support requests.
        
        \* Requests that fail to deliver the proper information may be closed without any feedback.
  
  - type: input
    id: segment 
    attributes:
      label: Segment
      description: |
        Which segment is this targeting? e.g.: type, method, field, or property
      placeholder: 
    validations:
      required: true
      
  - type: dropdown
    id: importancy
    attributes:
      label: Importancy
      description: |
        To your knowledge how would you describe the importancy of this feature?
      options:
        - Unknown
        - Nice extra
        - Missing details
        - Unclear or unintuitive
        - Incorrect
    validations:
      required: true
  
  - type: textarea
    id: improvement
    attributes:
      label: Improvement request
      description: |
        Tell us what needs to be changed to make this better, also add suggestions if you have any
    validations:
      required: true
  
  - type: textarea
    id: misc
    attributes:
      label: Extra
      description: |
        Anything else you'd like to add?
